
package mobiCRUD.WS;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CRUDImpl", targetNamespace = "http://WS.mobiSCD/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CRUDImpl {


    /**
     * 
     * @param senha
     * @param estado
     * @param cidade
     * @param endereco
     * @param ddd
     * @param nome
     * @param tel
     * @param id
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "adicionaUsuarios", targetNamespace = "http://WS.mobiSCD/", className = "mobiCRUD.WS.AdicionaUsuarios")
    @ResponseWrapper(localName = "adicionaUsuariosResponse", targetNamespace = "http://WS.mobiSCD/", className = "mobiCRUD.WS.AdicionaUsuariosResponse")
    @Action(input = "http://WS.mobiSCD/CRUDImpl/adicionaUsuariosRequest", output = "http://WS.mobiSCD/CRUDImpl/adicionaUsuariosResponse")
    public int adicionaUsuarios(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "nome", targetNamespace = "")
        String nome,
        @WebParam(name = "estado", targetNamespace = "")
        String estado,
        @WebParam(name = "cidade", targetNamespace = "")
        String cidade,
        @WebParam(name = "endereco", targetNamespace = "")
        String endereco,
        @WebParam(name = "DDD", targetNamespace = "")
        String ddd,
        @WebParam(name = "tel", targetNamespace = "")
        String tel,
        @WebParam(name = "senha", targetNamespace = "")
        String senha);

    /**
     * 
     * @return
     *     returns java.util.List<mobiCRUD.WS.StringArray>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscaUsuarios", targetNamespace = "http://WS.mobiSCD/", className = "mobiCRUD.WS.BuscaUsuarios")
    @ResponseWrapper(localName = "buscaUsuariosResponse", targetNamespace = "http://WS.mobiSCD/", className = "mobiCRUD.WS.BuscaUsuariosResponse")
    @Action(input = "http://WS.mobiSCD/CRUDImpl/buscaUsuariosRequest", output = "http://WS.mobiSCD/CRUDImpl/buscaUsuariosResponse")
    public List<StringArray> buscaUsuarios();

    /**
     * 
     * @param id
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeUsuarios", targetNamespace = "http://WS.mobiSCD/", className = "mobiCRUD.WS.RemoveUsuarios")
    @ResponseWrapper(localName = "removeUsuariosResponse", targetNamespace = "http://WS.mobiSCD/", className = "mobiCRUD.WS.RemoveUsuariosResponse")
    @Action(input = "http://WS.mobiSCD/CRUDImpl/removeUsuariosRequest", output = "http://WS.mobiSCD/CRUDImpl/removeUsuariosResponse")
    public int removeUsuarios(
        @WebParam(name = "id", targetNamespace = "")
        String id);

    /**
     * 
     * @param senha
     * @param estado
     * @param cidade
     * @param endereco
     * @param ddd
     * @param nome
     * @param tel
     * @param id
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editaUsuarios", targetNamespace = "http://WS.mobiSCD/", className = "mobiCRUD.WS.EditaUsuarios")
    @ResponseWrapper(localName = "editaUsuariosResponse", targetNamespace = "http://WS.mobiSCD/", className = "mobiCRUD.WS.EditaUsuariosResponse")
    @Action(input = "http://WS.mobiSCD/CRUDImpl/editaUsuariosRequest", output = "http://WS.mobiSCD/CRUDImpl/editaUsuariosResponse")
    public int editaUsuarios(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "nome", targetNamespace = "")
        String nome,
        @WebParam(name = "estado", targetNamespace = "")
        String estado,
        @WebParam(name = "cidade", targetNamespace = "")
        String cidade,
        @WebParam(name = "endereco", targetNamespace = "")
        String endereco,
        @WebParam(name = "DDD", targetNamespace = "")
        String ddd,
        @WebParam(name = "tel", targetNamespace = "")
        String tel,
        @WebParam(name = "senha", targetNamespace = "")
        String senha);

}
